AWSTemplateFormatVersion: '2010-09-09'
Description: IAM Roles Stack 

Resources:
  IAMRoleForLambdas:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument: 
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - 'lambda.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Description: This is the IAM Role for Lambdas
      Path: /
      Policies: 
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'
      RoleName: IAMRoleForLambdas

Outputs:

    IAMRoleForLambdasOutput:
        Value: !GetAtt ["IAMRoleForLambdas", "Arn"] 
        Export:
          Name: IAMRoleForLambdasARN
