AWSTemplateFormatVersion: '2010-09-09'
Description: SSM Stack 

Resources:
  SiteDBCredentials:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: DB Credentials
      Name: _SiteDBCredentials
      SecretString: !Sub 
        - '{"username": "${username}", "password": "${password}", "host": "${host}"}'
        - { username: !ImportValue DBMasterUsername, password: !ImportValue DBMasterPassword, host: !ImportValue DBHost}
    